pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:code-editor-environment/codeui-backend.git
          - cd RepoName.git
          - git push --mirror git@github.com:peanuttfpg/CodeUI_API.git